// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetAgentGuardConfig() {
  return window['go']['main']['App']['GetAgentGuardConfig']();
}

export function GetApprovals() {
  return window['go']['main']['App']['GetApprovals']();
}

export function GetDaemonStatus() {
  return window['go']['main']['App']['GetDaemonStatus']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetMCPAudit() {
  return window['go']['main']['App']['GetMCPAudit']();
}

export function GetMCPClients() {
  return window['go']['main']['App']['GetMCPClients']();
}

export function GetMCPPolicy() {
  return window['go']['main']['App']['GetMCPPolicy']();
}

export function GetOpenClawConfig() {
  return window['go']['main']['App']['GetOpenClawConfig']();
}

export function GetProxyStats() {
  return window['go']['main']['App']['GetProxyStats']();
}

export function HandleApproval(arg1, arg2) {
  return window['go']['main']['App']['HandleApproval'](arg1, arg2);
}

export function RestartDaemon() {
  return window['go']['main']['App']['RestartDaemon']();
}

export function SaveAgentGuardConfig(arg1) {
  return window['go']['main']['App']['SaveAgentGuardConfig'](arg1);
}

export function SaveMCPPolicy(arg1) {
  return window['go']['main']['App']['SaveMCPPolicy'](arg1);
}

export function SaveOpenClawConfig(arg1) {
  return window['go']['main']['App']['SaveOpenClawConfig'](arg1);
}

export function StartDaemon() {
  return window['go']['main']['App']['StartDaemon']();
}

export function StopDaemon() {
  return window['go']['main']['App']['StopDaemon']();
}

export function UnwrapMCPClient(arg1) {
  return window['go']['main']['App']['UnwrapMCPClient'](arg1);
}

export function UpdateDaemon() {
  return window['go']['main']['App']['UpdateDaemon']();
}

export function WrapMCPClient(arg1) {
  return window['go']['main']['App']['WrapMCPClient'](arg1);
}
