// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate():Promise<string>;

export function GetAgentGuardConfig():Promise<string>;

export function GetApprovals():Promise<string>;

export function GetDaemonStatus():Promise<string>;

export function GetLogs(arg1:number):Promise<string>;

export function GetMCPAudit():Promise<string>;

export function GetMCPClients():Promise<string>;

export function GetMCPPolicy():Promise<string>;

export function GetOpenClawConfig():Promise<string>;

export function GetProxyStats():Promise<string>;

export function HandleApproval(arg1:string,arg2:string):Promise<string>;

export function RestartDaemon():Promise<string>;

export function SaveAgentGuardConfig(arg1:string):Promise<string>;

export function SaveMCPPolicy(arg1:string):Promise<string>;

export function SaveOpenClawConfig(arg1:string):Promise<string>;

export function StartDaemon():Promise<string>;

export function StopDaemon():Promise<string>;

export function UnwrapMCPClient(arg1:string):Promise<string>;

export function UpdateDaemon():Promise<string>;

export function WrapMCPClient(arg1:string):Promise<string>;
